root = "."
tmp_dir = "tmp"

[build]
bin = "tmp\\main.exe"
cmd = "go build -o tmp/main.exe ."
full_bin = "B:/my-projects/goNote/tmp/main.exe"
# full_bin = "D:/buwu/goNote/tmp/main.exe"
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go"]

[log]
silent = false
time = false
