# Go için base image
FROM golang:1.23.2-alpine
# Çalışma dizinini ayarla
WORKDIR /app
# go.mod ve go.sum dosyalarını kopyala
COPY go.mod go.sum ./
# Bağımlılıkları indir
RUN go mod download
# Kalan dosyaları kopyala
COPY . .

RUN ls -la /app

RUN go build -o out .
# Uygulamanın çalışacağı port
EXPOSE 5000
CMD ["./out"]

