# Base image for Go
FROM golang:1.23.2-alpine

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the remaining application files
COPY . .

# Build the Go application and output the binary as 'app'
RUN go build -o app .

# Expose the port that the application will run on
EXPOSE 5000

# Run the application
CMD ["./app"]
